name: R-CMD-check

# The yml command runs whenever we push or pull our branch of the git repo.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# specify what the job and what the environment it runs in.
jobs:
  test:
    runs-on: ubuntu-latest

# specific steps of the yml commands.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
          
      - name: Install dependencies
        working-directory: dataVizModelR
        run: |
          Rscript -e "install.packages('devtools')"
          Rscript -e "devtools::install()"

      - name: Run tests
        working-directory: dataVizModelR
        run: |
          Rscript -e "devtools::test()"

      - name: Render documentations
        working-directory: dataVizModelR
        run: |
          Rscript -e "devtools::document()"
      
      - name: Render vignettes
        working-directory: dataVizModelR
        run: |
          Rscript -e "devtools::build_vignettes"
      
      - name: Build pkgdown site
        run: Rscript -e "pkgdown::build_site()"