name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      R_LIBS_USER: ${{ runner.temp }}/Rlibs
      TZ: UTC
      _R_CHECK_SYSTEM_CLOCK_: FALSE
      NOT_CRAN: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      - name: Install helper R packages
        run: |
          Rscript -e 'dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)'
          Rscript -e '.libPaths(Sys.getenv("R_LIBS_USER")); install.packages(c("remotes", "devtools"), repos = "https://cran.rstudio.com")'

      - name: Install package dependencies
        working-directory: dataVizModelR
        run: |
          Rscript -e '.libPaths(Sys.getenv("R_LIBS_USER")); remotes::install_deps(dependencies = TRUE, type = "both")'

      - name: Verify devtools is installed
        run: |
          Rscript -e '.libPaths(Sys.getenv("R_LIBS_USER")); stopifnot("devtools" %in% rownames(installed.packages()))'

      - name: Run tests
        working-directory: dataVizModelR
        run: |
          Rscript -e '.libPaths(Sys.getenv("R_LIBS_USER")); devtools::test()'

      - name: Render documentation
        working-directory: dataVizModelR
        run: |
          Rscript -e '.libPaths(Sys.getenv("R_LIBS_USER")); devtools::document()'

      - name: Render vignettes
        working-directory: dataVizModelR
        run: |
          Rscript -e '.libPaths(Sys.getenv("R_LIBS_USER")); devtools::build_vignettes()'

      - name: Build pkgdown site
        working-directory: dataVizModelR
        run: |
          Rscript -e '.libPaths(Sys.getenv("R_LIBS_USER")); pkgdown::build_site()'
