name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev libfreetype6-dev

      - name: Install R dependencies
        working-directory: dataVizModelR
        run: |
          install.packages(c("remotes", "usethis", "pkgdown", "rcmdcheck", "rversions", "urlchecker"))
          remotes::install_deps(dependencies = TRUE)

      - name: Run tests
        working-directory: dataVizModelR
        run: Rscript -e "devtools::test()"

      - name: Render documentation
        working-directory: dataVizModelR
        run: Rscript -e "devtools::document()"

      - name: Render vignettes
        working-directory: dataVizModelR
        run: Rscript -e "devtools::build_vignettes()"

      - name: Build pkgdown site
        working-directory: dataVizModelR
        run: Rscript -e "pkgdown::build_site()"
