name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up pandoc (required for vignettes)
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install renv and restore project library
        run: |
          Rscript -e 'install.packages("renv", repos = "https://cloud.r-project.org")'
          Rscript -e 'renv::restore()'

      - name: Install additional tools (outside renv, just in case)
        run: |
          Rscript -e 'install.packages(c("devtools", "roxygen2", "rmarkdown", "knitr", "testthat"), repos = "https://cloud.r-project.org")'

      - name: Run devtools::check()
        run: |
          Rscript -e 'devtools::check(document = TRUE, build_vignettes = TRUE, error_on = "warning")'
