name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install devtools
        run: |
          Rscript -e 'install.packages("devtools", repos = "https://cran.rstudio.com")'

      - name: Install package (with dependencies)
        working-directory: dataVizModelR
        run: |
          Rscript -e 'devtools::install(dependencies = TRUE)'

      - name: Run tests
        working-directory: dataVizModelR
        run: |
          Rscript -e 'devtools::test()'

      - name: Render documentation
        working-directory: dataVizModelR
        run: |
          Rscript -e 'devtools::document()'

      - name: Build vignettes
        working-directory: dataVizModelR
        run: |
          Rscript -e 'devtools::build_vignettes()'

      - name: Build site
        working-directory: dataVizModelR
        run: |
          Rscript -e 'install.packages("pkgdown", repos = "https://cran.rstudio.com"); pkgdown::build_site()'
