name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev

      - name: Install R dependencies (including devtools and friends)
        working-directory: dataVizModelR
        run: |
          Rscript -e 'install.packages(c("remotes", "usethis", "pkgdown", "rcmdcheck", "rversions", "urlchecker"))'
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Run tests
        working-directory: dataVizModelR
        run: |
          Rscript -e "devtools::test()"

      - name: Render documentation
        working-directory: dataVizModelR
        run: |
          Rscript -e "devtools::document()"

      - name: Render vignettes
        working-directory: dataVizModelR
        run: |
          Rscript -e "devtools::build_vignettes()"

      - name: Build pkgdown site
        working-directory: dataVizModelR
        run: |
          Rscript -e "pkgdown::build_site()"
